dbfilename redis_queue.rdb
dir /home/mahmoudtawfeek/task-manger/config/pids
pidfile /home/mahmoudtawfeek/task-manger/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/mahmoudtawfeek/task-manger/config/redis_queue.acl
